// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAppTTVqh6DBBYcUaivq4o8dwZ7E0IsRWQ',
    appId: '1:195650355363:web:0c52d182513fb50ab83f16',
    messagingSenderId: '195650355363',
    projectId: 'vertizontal-media',
    authDomain: 'vertizontal-media.firebaseapp.com',
    storageBucket: 'vertizontal-media.firebasestorage.app',
    measurementId: 'G-1N8R9JZTTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOpNjMzGlw80fxO2Ygl6oM5UsfSurR7zI',
    appId: '1:195650355363:android:5aacc858e9341115b83f16',
    messagingSenderId: '195650355363',
    projectId: 'vertizontal-media',
    storageBucket: 'vertizontal-media.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE69uTzU6Xm6ZnCUEUFAb5CJ9HHriou1M',
    appId: '1:195650355363:ios:4eb8ee7e3e088515b83f16',
    messagingSenderId: '195650355363',
    projectId: 'vertizontal-media',
    storageBucket: 'vertizontal-media.firebasestorage.app',
    iosBundleId: 'com.wVertiZontalMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE69uTzU6Xm6ZnCUEUFAb5CJ9HHriou1M',
    appId: '1:195650355363:ios:baceaf695cba1794b83f16',
    messagingSenderId: '195650355363',
    projectId: 'vertizontal-media',
    storageBucket: 'vertizontal-media.firebasestorage.app',
    iosBundleId: 'com.wVertiZontalMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAppTTVqh6DBBYcUaivq4o8dwZ7E0IsRWQ',
    appId: '1:195650355363:web:4761ba49d9133a9bb83f16',
    messagingSenderId: '195650355363',
    projectId: 'vertizontal-media',
    authDomain: 'vertizontal-media.firebaseapp.com',
    storageBucket: 'vertizontal-media.firebasestorage.app',
    measurementId: 'G-9RVGD140SD',
  );

}