// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0MRwo06_2joagvXtYblZiQsYFQ0OnCqw',
    appId: '1:83372535506:web:e23383740290b2fa70870b',
    messagingSenderId: '83372535506',
    projectId: 'notes-cf529',
    authDomain: 'notes-cf529.firebaseapp.com',
    storageBucket: 'notes-cf529.firebasestorage.app',
    measurementId: 'G-E8QHF18VK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR6FE3xNlS_vfp1TMnfXOwehkhYb3l3yg',
    appId: '1:83372535506:android:b97afc8fc87f7c3d70870b',
    messagingSenderId: '83372535506',
    projectId: 'notes-cf529',
    storageBucket: 'notes-cf529.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLCdsrWiFhdQbST6opapdHj46ZE1YSNLw',
    appId: '1:83372535506:ios:3b3ee55343b9baac70870b',
    messagingSenderId: '83372535506',
    projectId: 'notes-cf529',
    storageBucket: 'notes-cf529.firebasestorage.app',
    iosBundleId: 'com.example.raptureready',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLCdsrWiFhdQbST6opapdHj46ZE1YSNLw',
    appId: '1:83372535506:ios:3b3ee55343b9baac70870b',
    messagingSenderId: '83372535506',
    projectId: 'notes-cf529',
    storageBucket: 'notes-cf529.firebasestorage.app',
    iosBundleId: 'com.example.raptureready',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0MRwo06_2joagvXtYblZiQsYFQ0OnCqw',
    appId: '1:83372535506:web:d90c0d5fc5cdeec470870b',
    messagingSenderId: '83372535506',
    projectId: 'notes-cf529',
    authDomain: 'notes-cf529.firebaseapp.com',
    storageBucket: 'notes-cf529.firebasestorage.app',
    measurementId: 'G-TFHDCP6YGQ',
  );
}
